# ─────────────────────────────────────────────────────────────
# 开发镜像：Go + air 热重载
# 使用方式：docker compose up
# ─────────────────────────────────────────────────────────────
FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/library/golang:1.26.1




ENV TZ=Asia/Shanghai \
	GOPROXY=https://goproxy.cn,direct \
	GOSUMDB=off



WORKDIR /app

EXPOSE 8080


